import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import AlbumsList from "../components/AlbumsList";
import { gqlClient, QUERY_ALBUMS } from "../src/api";
import styles from "../styles/Home.module.css";
import { Props } from "../types/albums";

export const getServerSideProps = async () => {
  const { getAlbums: data } = await gqlClient.request(QUERY_ALBUMS);

  return {
    props: {
      data,
    },
  };
};

const albums: NextPage<Props> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Album Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Albums</h1>
        <Link href={"/"}>Go Home</Link>
        <AlbumsList data={data} list={true} />
      </main>
    </div>
  );
};

export default albums;
