import { NextPage } from "next";
import Head from "next/head";
import AlbumsList from "../../components/AlbumsList";
import { gqlClient, QUERY_ALBUM } from "../../src/api";
import styles from "../../styles/Home.module.css";
import { Props } from "../../types/albums";

export const getServerSideProps = async ({ params }: { params: any }) => {
  const data = await gqlClient.request(QUERY_ALBUM, params);

  return {
    props: {
      data: [data.getAlbum],
    },
  };
};

const SingleAlbums: NextPage<Props> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>See Album { data[0].id }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Album</h1>
        <AlbumsList data={data} list={false} />
      </main>
    </div>
  );
};

export default SingleAlbums;
